CARS: /home/nicola/Dropbox/Progetto SOL/CARS_terfram/src/stringparser.h File Reference
/home/nicola/Dropbox/Progetto SOL/CARS_terfram/src/stringparser.h File Reference
Definizione delle funzioni per il parser delle stringhe utilizzate nel grafo.
#include "dgraph.h"
Functions
bool_t is_correct_labelarray (unsigned int array_size, char **label_array)
Utilizzo mediante le espressioni regolari.
bool_t str_pars (char *e, char *origin, char *destin, double *km)
Detailed Description
Definizione delle funzioni per il parser delle stringhe utilizzate nel grafo.
Author:
Nicola Corti
Si dichiara che il contenuto di questo file e' in ogni sua parte opera originale dell' autore.
Function Documentation
bool_t is_correct_labelarray (unsigned int array_size, char ** label_array)
Utilizzo mediante le espressioni regolari.
Se si setta la macro REG_EXPR_MODE, la correttezza di un arco viene effettuata mediante l'esecuzione delle espressioni regolari.
Tale funzione e' inserita solo a scopo didattico, e pertanto se ne sconsiglia l'uso, dato che rende piu' pesante l'elaborazione delle stringhe. verifica se l'array di nody passato, e' un array corretto di etichette
Parameters:
array_size dimensione dell'array
label_array array di etichette
Return values:
TRUE se l'array e' un array di etichette valide
FALSE se l'array non e' un array di etichette valide
References FALSE, is_correct_label(), and TRUE.
Referenced by new_graph().
bool_t str_pars (char * e, char * origin, char * destin, double * km)
verifica se la stringa relativa all'arco e' corretta
Parameters:
e stringa relativa all'arco, del tipo "PARTENZA:ARRIVO:123.456"
origin buffer dove verra' scritta l'etichetta della citta di partenza
destin buffer dove verra' scritta l'etichetta della citta di destinazione
km puntatore ad una variabile double, dove verra' scritta la distanza
Return values:
TRUE se la stringa e' un arco valido
FALSE se si e' verificato un errore
References FALSE, is_correct_label(), is_double(), LLABEL, MALLOC_ERRNO, and TRUE.
Referenced by add_edge().