CARS: /home/nicola/Dropbox/Progetto SOL/CARS_terfram/src/test-dgraph.c File Reference
/home/nicola/Dropbox/Progetto SOL/CARS_terfram/src/test-dgraph.c File Reference
test su grafo stradale diretto
#include <stdio.h>
#include <stdlib.h>
#include <errno.h>
#include <mcheck.h>
#include "dgraph.h"
Defines
#define NODESFILE "./CITY.txt"
#define ARCSFILE "./TUSCANY.map"
#define NODESFILE1 "./outcitta.txt"
#define ARCSFILE1 "./outstrade.map"
#define END (-1)
Functions
int main (void)
Variables
static char * citta []
static char * strade []
static char * stradeerr []
static int deg []
Detailed Description
test su grafo stradale diretto
Author:
lso11
Define Documentation
#define ARCSFILE "./TUSCANY.map"
file dati mappa toscana: file archi
Referenced by main().
#define ARCSFILE1 "./outstrade.map"
file scrittura mappa toscana: file archi
Referenced by main().
#define END (-1)
terminatore file di controllo test degree()
#define NODESFILE "./CITY.txt"
file dati mappa toscana: file nodi
Referenced by main().
#define NODESFILE1 "./outcitta.txt"
file scrittura mappa toscana: file nodi
Referenced by main().
Function Documentation
int main (void)
main function
References add_edge(), ARCSFILE, ARCSFILE1, citta, copy_graph(), deg, degree(), e_size(), free_graph(), is_edge(), is_node(), load_graph(), n_size(), new_graph(), NODESFILE, NODESFILE1, print_graph(), save_graph(), strade, and stradeerr.
Variable Documentation
char* citta[] [static]
Initial value:
 {
    "PISA",
    "LUCCA",
    "SIENA",
    "LIVORNO",
    "LA SPEZIA",
    "GROSSETO",
    "AREZZO",
    "PRATO",
    "FIRENZE",
    NULL,
}
nodi primo grafo di test
Referenced by main().
int deg[] [static]
Initial value:
 {
    2,
    1,
    2,
    1,
    1,
    0,
    1,
    2,
    2,
    END,
}
degree nodi corretto primo grafo di test
Referenced by main().
char* strade[] [static]
Initial value:
 {
  "PISA:LUCCA:24.8",
  "LUCCA:PISA:24.8",
  "PISA:LIVORNO:22.3",
  "LIVORNO:PISA:22.3",
  "LA SPEZIA:PISA:80.0",
  "SIENA:GROSSETO:90.6",
  "FIRENZE:AREZZO:77.9",
  "AREZZO:FIRENZE:77.9",
  "PRATO:LUCCA:57.9",
  "SIENA:FIRENZE:56.1",
  "FIRENZE:PRATO:24.9",
  "PRATO:FIRENZE:24.9",
  NULL,
}
archi corretti primo grafo di test
Referenced by main().
char* stradeerr[] [static]
Initial value:
 {
  "PISA:COSENZA:24.8",
  "PISA:COSENZA:CICCIOBELLO",
  "LUCCA:PISA:",
  "PISA",
  NULL,
}
archi errati primo grafo di test
Referenced by main().